# Generated by Django 3.2.9 on 2021-12-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('information', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/%Y/%M/%d/main')),
                ('imag1', models.ImageField(upload_to='images/%Y/%M/%d/1')),
                ('imag2', models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%d/2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%d/3')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('num_exists', models.PositiveIntegerField()),
                ('exists', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('tags', models.ManyToManyField(to='home.Tags')),
            ],
        ),
    ]
