# Generated by Django 3.2.9 on 2021-12-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211212_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=5)),
            ],
        ),
    ]
