# Generated by Django 3.2.9 on 2021-12-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bookamrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookamrk',
            name='status',
            field=models.CharField(choices=[('yse', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
