# Generated by Django 3.2.9 on 2021-12-22 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20211221_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adrress_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(max_length=12)),
                ('home_phone', models.PositiveIntegerField(max_length=8)),
                ('postal_code', models.PositiveIntegerField(max_length=12)),
                ('adrress', models.TextField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adrress_order', to='home.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adrress_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
