# Generated by Django 3.2.9 on 2021-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_adrress_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrress_model',
            name='home_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adrress_model',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adrress_model',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
