# Generated by Django 3.2.9 on 2021-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211223_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrress_model',
            name='home_phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adrress_model',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adrress_model',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
