# Generated by Django 3.2.9 on 2022-01-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211231_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub',
            field=models.BooleanField(default=False),
        ),
    ]
