# Generated by Django 3.2.9 on 2022-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_category_category_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imag1',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%d/1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%d/main'),
        ),
    ]
