# Generated by Django 3.2.9 on 2022-01-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imag1',
            field=models.ImageField(default='avatar.png', upload_to='images/%Y/%M/%d/1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imag2',
            field=models.ImageField(default='avatar.png', upload_to='images/%Y/%M/%d/2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='images/%Y/%M/%d/main'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='avatar.png', upload_to='images/%Y/%M/%d/3'),
        ),
    ]
